export enum AdminPermissions {
  CreateAssessment = "createAssessment",
  UpdateAssessment = "updateAssessment",
  DeleteAssessment = "deleteAssessment",
  UpdateUser = "updateUser",
  UpdateCompany = "updateCompany",
  UpdateAdmin = "updateAdmin",
  UpdateUserCircle = "updateUserCircle",
  UpdateCompanyCircle = "updateCompanyCircle",
  ReadUser = "readUser",
  ReadCompany = "readCompany",
  ReadAdmin = "readAdmin",
  ReadUserCircle = "readUserCircle",
  ReadCompanyCircle = "readCompanyCircle",
  DeleteUser = "deleteUser",
  DeleteCompany = "deleteCompany",
  DeleteAdmin = "deleteAdmin",
  DeleteUserCircle = "deleteUserCircle",
  DeleteCompanyCircle = "deleteCompanyCircle",
}
